"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var Test_module_scss_1 = require("../Test.module.scss");
var MessageBar_1 = require("office-ui-fabric-react/lib/MessageBar");
var Test = /** @class */ (function (_super) {
    __extends(Test, _super);
    function Test() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Test.prototype.render = function () {
        var peopleList = [];
        if (this.props && this.props.people)
            peopleList = this.props.people;
        var lists = [];
        if (this.props && this.props.listsCollection)
            lists = this.props.listsCollection;
        return (React.createElement("div", { className: Test_module_scss_1.default.test },
            React.createElement("div", { className: Test_module_scss_1.default.container },
                React.createElement("div", null,
                    React.createElement("div", { style: { backgroundColor: this.props.color, fontFamily: this.props.font, fontSize: this.props.fontSize ? this.props.fontSize : '12px', padding: '20px' } },
                        React.createElement(MessageBar_1.MessageBar, null, "Edit this WebPart to test the custom fields."),
                        React.createElement("p", { className: "ms-fontSize-xxl" },
                            React.createElement("i", { className: "ms-Icon ms-Icon--ClearFormatting", "aria-hidden": "true" }),
                            "\u00A0 Layout Fields"),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--Font", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Font"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldfontpicker", target: "_doc" }, "(Doc)"),
                            " : \u00A0",
                            this.props.font),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--FontSize", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Font Size"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldfontsizepicker", target: "_doc" }, "(Doc)"),
                            " : \u00A0",
                            this.props.fontSize),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--Color", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Color (Mini)"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldcolorpickermini", target: "_doc" }, "(Doc)"),
                            " : \u00A0",
                            this.props.miniColor),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--Color", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Color"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldcolorpicker", target: "_doc" }, "(Doc)"),
                            " : \u00A0",
                            this.props.color),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--Waffle", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Icon"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldiconpicker", target: "_doc" }, "(Doc)"),
                            " : \u00A0",
                            React.createElement("i", { className: 'ms-Icon ' + this.props.icon, "aria-hidden": "true", style: { fontSize: 'large' } }),
                            "\u00A0",
                            this.props.icon),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--AlignLeft", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Align"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldalignpicker", target: "_doc" }, "(Doc)"),
                            " : \u00A0",
                            this.props.align),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--FullScreen", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Dimension"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfielddimensionpicker", target: "_doc" }, "(Doc)"),
                            " : \u00A0",
                            this.props.dimension != null ? this.props.dimension.width + ' x ' + this.props.dimension.height : ''),
                        React.createElement("p", { className: "ms-fontSize-xxl" },
                            React.createElement("i", { className: "ms-Icon ms-Icon--InsertTextBox", "aria-hidden": "true" }),
                            "\u00A0 Text Input Fields"),
                        React.createElement("div", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--ChevronDown", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "DropDown Select"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfielddropdownselect", target: "_doc" }, "(Doc)"),
                            " : \u00A0",
                            React.createElement("ul", null, this.props.dropDownSelect != null ?
                                this.props.dropDownSelect.map(function (element, i) {
                                    return (React.createElement("li", { key: i }, element));
                                })
                                : '')),
                        React.createElement("div", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--List", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Sortable List"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldsortablelist", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            React.createElement("ul", null, this.props.sortableList != null ?
                                this.props.sortableList.map(function (element, i) {
                                    return (React.createElement("li", { key: i }, element));
                                })
                                : '')),
                        React.createElement("div", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--Breadcrumb", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "DropDown Treeview"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfielddropdowntreeview", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            React.createElement("ul", null, this.props.dropDownTreeView != null ?
                                this.props.dropDownTreeView.map(function (element, i) {
                                    return (React.createElement("li", { key: i }, element));
                                })
                                : '')),
                        React.createElement("div", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--Breadcrumb", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Treeview"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldtreeview", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            React.createElement("ul", null, this.props.treeView != null ?
                                this.props.treeView.map(function (element, i) {
                                    return (React.createElement("li", { key: i }, element));
                                })
                                : '')),
                        React.createElement("div", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--Tag", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Tags"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldtagpicker", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            React.createElement("ul", null, this.props.tags != null ?
                                this.props.tags.map(function (element, i) {
                                    return (React.createElement("li", { key: i }, element.name));
                                })
                                : '')),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--List", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Custom List"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldcustomlist", target: "_doc" }, "(Doc)"),
                            " : \u00A0",
                            JSON.stringify(this.props.customList)),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--FavoriteStarFill", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Star Rating"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldstarrating", target: "_doc" }, "(Doc)"),
                            " : \u00A0",
                            this.props.starRating),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--Lock", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Password"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldpassword", target: "_doc" }, "(Doc)"),
                            " : \u00A0",
                            this.props.password),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--NumberField", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Auto Complete Text"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldautocomplete", target: "_doc" }, "(Doc)"),
                            " : \u00A0",
                            this.props.autoSuggest),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--NumberField", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Number"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldnumericinput", target: "_doc" }, "(Doc)"),
                            " : \u00A0",
                            this.props.numeric),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--Font", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Rich Text Box"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldrichtextbox", target: "_doc" }, "(Doc)"),
                            " : \u00A0",
                            this.props.richTextBox),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--CalendarWorkWeek", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Date"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfielddatepicker", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            this.props.date),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--CalendarWorkWeek", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Date ISO"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfielddatepicker", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            this.props.date2),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--CalendarWorkWeek", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Date Time"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfielddatetimepicker", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            this.props.datetime),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--CalendarWorkWeek", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Slider Range"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldsliderrange", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            this.props.sliderRange),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--Phone", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Phone Number"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldphonenumber", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            this.props.phone),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--PaymentCard", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Credit Card"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldmaskedinput", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            this.props.maskedInput),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--MapPin", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Geolocation"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldmappicker", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            this.props.geolocation),
                        React.createElement("p", { className: "ms-fontSize-xxl" },
                            React.createElement("i", { className: "ms-Icon ms-Icon--DeveloperTools", "aria-hidden": "true" }),
                            "\u00A0 SharePoint Fields"),
                        React.createElement("div", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--PeopleAdd", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Users"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldpeoplepicker", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            React.createElement("ul", null, peopleList.map(function (element, i) {
                                return (React.createElement("li", { key: 'people' + i },
                                    "Username : ",
                                    element.fullName,
                                    React.createElement("br", null),
                                    "Login: ",
                                    element.login,
                                    React.createElement("br", null),
                                    "Email: ",
                                    element.email,
                                    React.createElement("br", null),
                                    "JobTitle: ",
                                    element.jobTitle,
                                    React.createElement("br", null)));
                            }))),
                        React.createElement("div", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--PeopleAdd", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Groups"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldgrouppicker", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            React.createElement("ul", null, this.props.groups !== undefined ? this.props.groups.map(function (element, i) {
                                return (React.createElement("li", { key: 'groups' + i },
                                    "FullName : ",
                                    element.fullName,
                                    React.createElement("br", null),
                                    "Description: ",
                                    element.description,
                                    React.createElement("br", null),
                                    "Login: ",
                                    element.login,
                                    React.createElement("br", null),
                                    "ID: ",
                                    element.id,
                                    React.createElement("br", null)));
                            }) : '')),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--Picture", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Picture"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldpicturepicker", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            this.props.picture),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--Document", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Document"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfielddocumentepicker", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            this.props.document),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--VideoSolid", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Office Video"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldofficevideopicker", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            this.props.officeVideo),
                        React.createElement("div", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--Search", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Search Properties"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldsearchpropertiespicker", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            React.createElement("ul", null, this.props.searchProperties !== undefined ? this.props.searchProperties.map(function (element, i) {
                                return (React.createElement("li", { key: 'groups' + i },
                                    element,
                                    React.createElement("br", null)));
                            }) : '')),
                        React.createElement("div", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--Tag", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Term Sets"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldtermsetpicker", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            React.createElement("ul", null, this.props.termSets !== undefined ? this.props.termSets.map(function (element, i) {
                                return (React.createElement("li", { key: 'groups' + i },
                                    "Name: ",
                                    element.Name,
                                    ", Guid: ",
                                    element.Guid,
                                    ", TermStore Guid: ",
                                    element.TermStoreGuid,
                                    React.createElement("br", null)));
                            }) : '')),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--List", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "List"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldsplistpicker", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            this.props.list),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--List", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Query"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldsplistquery", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            this.props.query),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--List", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Display Mode"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfielddisplaymode", target: "_doc" }, "(Doc)"),
                            " : \u00A0",
                            this.props.displayMode),
                        React.createElement("p", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--FolderSearch", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Folder"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldspfolderpicker", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            this.props.folder),
                        React.createElement("div", null,
                            React.createElement("i", { className: "ms-Icon ms-Icon--List", "aria-hidden": "true" }),
                            "\u00A0",
                            React.createElement("b", null, "Lists"),
                            "\u00A0",
                            React.createElement("a", { className: "ms-fontSize-sPlus", href: "https://oliviercc.github.io/sp-client-custom-fields/propertyfieldsplistmultiplepicker", target: "_doc" }, "(Doc)"),
                            " :\u00A0",
                            React.createElement("ul", null, lists.map(function (element, i) {
                                return (React.createElement("li", { key: 'list' + i }, element));
                            }))))))));
    };
    return Test;
}(React.Component));
exports.default = Test;
//# sourceMappingURL=Test.js.map